services:
  - type: web
    name: core-recon-backend
    env: docker
    repo: https://github.com/SamFrieman/core-recon
    branch: main
    plan: free
    buildCommand: ""
    startCommand: "uvicorn backend.main:app --host 0.0.0.0 --port $PORT"
    dockerfilePath: backend/Dockerfile
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
